#!/usr/bin/perl
#
# Copyright (c) 2010  S2 Factory, Inc.  All rights reserved.
#
# $Id$
#
#%# family=auto
#%# capabilities=autoconf

use strict;
use warnings;
use Munin::Plugin;
use Data::Dumper;
use MIME::Base64;
use Storable qw(freeze thaw);

my $poll_interval = 300;	# 300 seconds
my $plugin_name   = 'kumofs';
my $kumostat      = '/usr/local/bin/kumostat';
my $cmd           = $ARGV[0] || '';

do_autoconf($kumostat) if ($cmd eq 'autoconf');

do_config() if ($cmd eq 'config');

do_print();

exit 0;

# ============================================================
sub do_autoconf {
    my ($kumostat) = @_;
    if (not -x $kumostat) {
	print "no (require kumostat(1))\n";
	exit 1;
    }
    print "yes\n";
    exit 0;
}

sub do_config {
    print <<"EOF";

graph_title kumofs item counts
graph_args --base 1000 --lower-limit 0
graph_vlabel total items
graph_category kumofs
items.label items
items.type GAUGE
items.info Number of items in kumo-server

EOF
    exit 0;
}

sub do_print {
    my @val = map { chomp; $_ } (`$kumostat localhost items`);
    printf <<EOF, @val;
items.value %d
EOF
    return;
}

# Local Variables:
# cperl-indent-level: 4
# End:
